PG_CONFIG:
  name: "nest-demo-pg"
  type: "postgres"
  host: "119.3.214.158"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "ds-cash"
  entities: "pg" # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true

APP_CONFIG:
  jwt_secret: 'secretKey' # jwt 秘钥
  jwt_expire: '8h' # jwt 时效时间